This files is created for the ease of data analysis. Using this Jupyter notebook to understand some of the behaviour or pattern if the excel sheets.

In [4]:
## common library for data cleaning or analyse data
import pandas as pd
import numpy as np
import seaborn as sns


# print to hint you have completed the import of libraries
# if you dont see the message below, you may have to check your python lib
print("Hello World - you have successfully imported libraries!!")

## e.g.
# pip install pandas
#  pip install numpy
#  pip install seaborn
#  pip install matplotlib

Hello World - you have successfully imported libraries!!

My first loading of a csv file. Using pd to read and showing basic information as show in below code section.

In [11]:
arabica = pd.read_csv("../src/main/resources/data/arabica_data_cleaned.csv")

# explain the data info, in total should see columns described in "../src/main/resources/data/README.md"
arabica.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1311 entries, 0 to 1310
Data columns (total 44 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             1311 non-null   int64
 1   Species                1311 non-null   object
 2   Owner                  1304 non-null   object
 3   Country.of.Origin      1310 non-null   object
 4   Farm.Name              955 non-null    object
 5   Lot.Number             270 non-null    object
 6   Mill                   1001 non-null   object
 7   ICO.Number             1163 non-null   object
 8   Company                1102 non-null   object
 9   Altitude               1088 non-null   object
 10  Region                 1254 non-null   object
 11  Producer               1081 non-null   object
 12  Number.of.Bags         1311 non-null   int64
 13  Bag.Weight             1311 non-null   object
 14  In.Country.Partner     1311 non-null   object
 15  Harvest.Year           1264 non-null   object
 16  Grading.Date           1311 non-null   object
 17  Owner.1                1304 non-null   object
 18  Variety                1110 non-null   object
 19  Processing.Method      1159 non-null   object
 20  Aroma                  1311 non-null   float64
 21  Flavor                 1311 non-null   float64
 22  Aftertaste             1311 non-null   float64
 23  Acidity                1311 non-null   float64
 24  Body                   1311 non-null   float64
 25  Balance                1311 non-null   float64
 26  Uniformity             1311 non-null   float64
 27  Clean.Cup              1311 non-null   float64
 28  Sweetness              1311 non-null   float64
 29  Cupper.Points          1311 non-null   float64
 30  Total.Cup.Points       1311 non-null   float64
 31  Moisture               1311 non-null   float64
 32  Category.One.Defects   1311 non-null   int64
 33  Quakers                1310 non-null   float64
 34  Color                  1044 non-null   object
 35  Category.Two.Defects   1311 non-null   int64
 36  Expiration             1311 non-null   object
 37  Certification.Body     1311 non-null   object
 38  Certification.Address  1311 non-null   object
 39  Certification.Contact  1311 non-null   object
 40  unit_of_measurement    1311 non-null   object
 41  altitude_low_meters    1084 non-null   float64
 42  altitude_high_meters   1084 non-null   float64
 43  altitude_mean_meters   1084 non-null   float64
dtypes: float64(16), int64(4), object(24)
memory usage: 450.8+ KB

In [14]:
# show the status of null value in cells.
arabica.isnull().sum()

Unnamed: 0                  0
Species                     0
Owner                       7
Country.of.Origin           1
Farm.Name                 356
Lot.Number               1041
Mill                      310
ICO.Number                148
Company                   209
Altitude                  223
Region                     57
Producer                  230
Number.of.Bags              0
Bag.Weight                  0
In.Country.Partner          0
Harvest.Year               47
Grading.Date                0
Owner.1                     7
Variety                   201
Processing.Method         152
Aroma                       0
Flavor                      0
Aftertaste                  0
Acidity                     0
Body                        0
Balance                     0
Uniformity                  0
Clean.Cup                   0
Sweetness                   0
Cupper.Points               0
Total.Cup.Points            0
Moisture                    0
Category.One.Defects        0
Quakers                     1
Color                     267
Category.Two.Defects        0
Expiration                  0
Certification.Body          0
Certification.Address       0
Certification.Contact       0
unit_of_measurement         0
altitude_low_meters       227
altitude_high_meters      227
altitude_mean_meters      227
dtype: int64

Simple analyse column/cells with numeric data using pd.describe().

In [12]:
# show analytics result of those column with numeric value.
arabica.describe()

,Unnamed: 0,Number.of.Bags,Aroma,Flavor,Aftertaste,Acidity,Body,Balance,Uniformity,Clean.Cup,Sweetness,Cupper.Points,Total.Cup.Points,Moisture,Category.One.Defects,Quakers,Category.Two.Defects,altitude_low_meters,altitude_high_meters,altitude_mean_meters
count,1311.000000,1311.000000,1311.000000,1311.000000,1311.000000,1311.000000,1311.000000,1311.000000,1311.000000,1311.00000,1311.000000,1311.000000,1311.000000,1311.000000,1311.000000,1310.000000,1311.000000,1084.000000,1084.000000,1084.000000
mean,656.000763,153.887872,7.563806,7.518070,7.397696,7.533112,7.517727,7.517506,9.833394,9.83312,9.903272,7.497864,82.115927,0.088863,0.426392,0.177099,3.591915,1759.548954,1808.843803,1784.196379
std,378.598733,129.733734,0.378666,0.399979,0.405119,0.381599,0.359213,0.406316,0.559343,0.77135,0.530832,0.474610,3.515761,0.047957,1.832415,0.840583,5.350371,8767.847252,8767.187498,8767.016913
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000
25%,328.500000,14.500000,7.420000,7.330000,7.250000,7.330000,7.330000,7.330000,10.000000,10.00000,10.000000,7.250000,81.170000,0.090000,0.000000,0.000000,0.000000,1100.000000,1100.000000,1100.000000
50%,656.000000,175.000000,7.580000,7.580000,7.420000,7.500000,7.500000,7.500000,10.000000,10.00000,10.000000,7.500000,82.500000,0.110000,0.000000,0.000000,2.000000,1310.640000,1350.000000,1310.640000
75%,983.500000,275.000000,7.750000,7.750000,7.580000,7.750000,7.670000,7.750000,10.000000,10.00000,10.000000,7.750000,83.670000,0.120000,0.000000,0.000000,4.000000,1600.000000,1650.000000,1600.000000
max,1312.000000,1062.000000,8.750000,8.830000,8.670000,8.750000,8.580000,8.750000,10.000000,10.00000,10.000000,10.000000,90.580000,0.280000,31.000000,11.000000,55.000000,190164.000000,190164.000000,190164.000000

Analyse some of the unique value. We can have drop it if the column only have a single value, so that we can have less dimension when analyse.

In [22]:
# Loop each columns from arabica

for col in arabica.columns:
    print(f"{col} has {len(arabica[col].unique())} unique values")

Unnamed: 0 has 1311 unique values
Species has 1 unique values
Owner has 306 unique values
Country.of.Origin has 37 unique values
Farm.Name has 558 unique values
Lot.Number has 222 unique values
Mill has 448 unique values
ICO.Number has 841 unique values
Company has 271 unique values
Altitude has 384 unique values
Region has 344 unique values
Producer has 676 unique values
Number.of.Bags has 130 unique values
Bag.Weight has 56 unique values
In.Country.Partner has 27 unique values
Harvest.Year has 47 unique values
Grading.Date has 558 unique values
Owner.1 has 310 unique values
Variety has 30 unique values
Processing.Method has 6 unique values
Aroma has 33 unique values
Flavor has 35 unique values
Aftertaste has 35 unique values
Acidity has 31 unique values
Body has 31 unique values
Balance has 32 unique values
Uniformity has 10 unique values
Clean.Cup has 11 unique values
Sweetness has 8 unique values
Cupper.Points has 42 unique values
Total.Cup.Points has 178 unique values
Moisture has 23 unique values
Category.One.Defects has 16 unique values
Quakers has 12 unique values
Color has 4 unique values
Category.Two.Defects has 38 unique values
Expiration has 557 unique values
Certification.Body has 26 unique values
Certification.Address has 30 unique values
Certification.Contact has 27 unique values
unit_of_measurement has 2 unique values
altitude_low_meters has 189 unique values
altitude_high_meters has 189 unique values
altitude_mean_meters has 202 unique values